### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by mb1986** [PepikVaio/reMarkable#1]
Hi @PepikVaio, could you please provide a license for the images in `reMarkable_hack/rm-hacks`? Without it I think I can't use them in rm-hacks repo.

Cheers!

**Comment by Eeems** [comment]
> Hi, I used the base from this repository and modified it to match your version.
> 
> I don't know how to write or grant a license. Anyway, you can do with the image as you need for me (that's why I provided it). But perhaps it would be right to ask the original owner.
> 
> https://github.com/RedTartan04/rmGesturesDoc

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Since you used the original files from another repository, you'll need to check the terms of its license for what license you can use. Since it doesn't have a license, you are currently in violation of their copyright if you don't have explicit permission to modify their file. As stated by the above link:

> ... without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by PepikVaio** [comment]
OK, my mistake - I am sorry.
I see you have already submitted a license request - thank you.

**Comment by PepikVaio** [comment]
I deleted to be safe so as not to violate copyright.
The original owner does not want to license:

https://github.com/RedTartan04/rmGesturesDoc/issues/1#issuecomment-1868465375
